//
//  ClaimIntroWorker.swift
//  Bomapp
//
//  Created by rowkaxl on 06/03/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import BomappDM

class ClaimIntroWorker {

    public func getClaimSectionModel() -> [ClaimSectionModel] {

        let model: [ClaimSectionModel] =
            [
                ClaimSectionModel(model: ClaimSectionID.section1,
                                  items: [
                                    ClaimModelItem(claimType: .headerTitle(title: "보험금 청구,\n보맵과 함께 간단히\n해결하세요".bdmSetting(customFont: Font.light.font(size: 32), height: 34, letterSpacing: -1.0, color: UIColor(rgb: 0x3c7ae5)))),
                                    ClaimModelItem(claimType: .empty(height: 4)),
                                    ClaimModelItem(claimType: .headerDescription(description: "보험금청구를 시작하기 전 구비서류안내를\n보시면 많은 도움이 됩니다.".bdmSetting(customFont: Font.medium.font(size: 14), height: 20, letterSpacing: -0.5, color: UIColor(rgb: 0xa4a4a4)))),
                                    ClaimModelItem(claimType: .empty(height: 8)),
                                    ClaimModelItem(claimType: .headerButton(buttonTitle: "간편청구 구비서류 안내")),
                                    ClaimModelItem(claimType: .headerButton(buttonTitle: "여행자보험 구비서류 안내"))
                    ])
        ]

        return model
    }
}
