//
//  ClaimIntroViewController.swift
//  Bomapp
//
//  Created by rowkaxl on 06/03/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxCocoa
import RxSwift
import BomappDM
import RxDataSources

protocol ClaimIntroDisplayLogic: class {
    func displaySectionModel(viewModel: ClaimIntro.SectionItem.ViewModel)
}

class ClaimIntroViewController: ClaimBaseViewController, ClaimIntroDisplayLogic {
    var interactor: ClaimIntroBusinessLogic?
    var router: (NSObjectProtocol & ClaimIntroRoutingLogic & ClaimIntroDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = ClaimIntroInteractor()
        let presenter = ClaimIntroPresenter()
        let router = ClaimIntroRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()

        interactor?.getSectionModel()
        configure()
    }

    private let disposeBag = DisposeBag()

    public let models = BehaviorRelay<[ClaimSectionModel]>(value: [])

    @IBOutlet weak var backBtn: UIButton!
    @IBOutlet weak var bottomBtn: UIButton! {
        didSet {
            bottomBtn.setDefaultBottomBtnAttribute()
        }
    }

    func displaySectionModel(viewModel: ClaimIntro.SectionItem.ViewModel) {
        models.accept(viewModel.claimSectionModel)
    }
}

extension ClaimIntroViewController {

    private func configure() {
        configureUI()
        configureRx()
    }

    private func configureUI() {

        self.buttonTabHandler = { title in
            switch title {
            case "간편청구 구비서류 안내": self.router?.routeToGuide(segue: nil)
            case "여행자보험 구비서류 안내": break
            default: break
            }
        }
    }

    private func configureRx() {
        models.bind(to: cv.rx.items(dataSource: dataSource)).disposed(by: self.disposeBag)

        self.backBtn.rx.tap
            .subscribe(onNext: {
                self.navigationController?.popViewController(animated: true)
            }).disposed(by: disposeBag)

        self.bottomBtn.rx.tap
            .subscribe(onNext: {
                self.router?.routeToSelectInsurance(segue: nil)
            }).disposed(by: disposeBag)
    }
}
