//
//  ClaimIntroPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 06/03/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClaimIntroPresentationLogic {
    func presentSectionModel(response: ClaimIntro.SectionItem.Response)
}

class ClaimIntroPresenter: ClaimIntroPresentationLogic {
    weak var viewController: ClaimIntroDisplayLogic?

    // MARK: Do something

    func presentSectionModel(response: ClaimIntro.SectionItem.Response) {
        let viewModel = ClaimIntro.SectionItem.ViewModel(claimSectionModel: response.claimSectionModel)
        viewController?.displaySectionModel(viewModel: viewModel)
    }
}
