//
//  ClaimGuideViewController.swift
//  Bomapp
//
//  Created by rowkaxl on 25/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxCocoa
import RxSwift
import BomappDM
import RxDataSources

protocol ClaimGuideDisplayLogic: class {
    func displaySectionModel(viewModel: ClaimGuide.SectionItem.ViewModel)
}

class ClaimGuideViewController: ClaimBaseViewController, ClaimGuideDisplayLogic {
    var interactor: ClaimGuideBusinessLogic?
    var router: (NSObjectProtocol & ClaimGuideRoutingLogic & ClaimGuideDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = ClaimGuideInteractor()
        let presenter = ClaimGuidePresenter()
        let router = ClaimGuideRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()

        interactor?.getSectionModel()
        configure()
    }

    private let disposeBag = DisposeBag()

    public let models = BehaviorRelay<[ClaimSectionModel]>(value: [])

    @IBOutlet weak var closeBtn: UIButton!

    func displaySectionModel(viewModel: ClaimGuide.SectionItem.ViewModel) {
        models.accept(viewModel.claimSectionModel)
    }
}

extension ClaimGuideViewController {

    private func configure() {
        configureUI()
        configureRx()
    }

    private func configureUI() {

    }

    private func configureRx() {
        models.bind(to: cv.rx.items(dataSource: dataSource)).disposed(by: self.disposeBag)

        self.closeBtn.rx.tap
            .subscribe(onNext: {
                self.dismiss(animated: true)
            }).disposed(by: disposeBag)
    }
}
