//
//  ClaimGuideWorker.swift
//  Bomapp
//
//  Created by rowkaxl on 25/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import BomappDM

class ClaimGuideWorker {

    public func getClaimSectionModel() -> [ClaimSectionModel] {

        var model: [ClaimSectionModel] =
            [
                ClaimSectionModel(model: ClaimSectionID.section1,
                                  items: [
                                    ClaimModelItem(claimType: .headerTitle(title: "진료 이용내역\n조회 기준을\n알려드립니다.".bdmSetting(customFont: Font.light.font(size: 32), height: 34, letterSpacing: -1.0, color: UIColor(rgb: 0x3c7ae5)))),
                                    ClaimModelItem(claimType: .empty(height: 4)),
                                    ClaimModelItem(claimType: .headerDescription(description: "진료 이용내역은 건강보험의 급여비용 중\n본인부담금만 표시됩니다.".bdmSetting(customFont: Font.medium.font(size: 14), height: 20, letterSpacing: -0.5, color: UIColor(rgb: 0xa4a4a4)))),
                                    ClaimModelItem(claimType: .empty(height: 20))
                    ])
        ]

        model.append(ClaimSectionModel(model: ClaimSectionID.section2,
                                       items: [
                                        ClaimModelItem(claimType: .guideDesc(numImage: #imageLiteral(resourceName: "05TagNum01"), description: "진료 이용내역은 회원님의 공인인증정보를 바탕으로 국민건강보험공단에서 조회한 결과입니다. 국민건강보험공단 홈페이지에서 직접 동일한 내용을 확인하실 수 있습니다.")),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .guideDesc(numImage: #imageLiteral(resourceName: "05TagNum02"), description: "보험금 청구를 위한 참고 자료이며, 건강보험의 급여비용 중 본인부담금만 표시되기 때문에 실제 지출하신 병원비 또는 약제비와 다릅니다. ")),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .guideDesc(numImage: #imageLiteral(resourceName: "05TagNum03"), description: "조회시점으로부터  약 2개월 이전에 이용한 내역부터 최근 1년간의 정보만 보여집니다.")),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .guideDesc(numImage: #imageLiteral(resourceName: "05TagNum04"), description: "민감한 상병이나 사생활 침해의 우려가 있는 정신과, 산부인과, 비뇨기과 등의 이용내역은 제공되지 않습니다.")),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .guideDesc(numImage: #imageLiteral(resourceName: "05TagNum05"), description: "보맵은 본 정보를 보험사 등 외부기관에 절대로 제공하지 않습니다. "))
            ]))

        return model
    }
}
