//
//  ClaimConfirmRouter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ClaimConfirmRoutingLogic {
    func routeToSendFax(segue: UIStoryboardSegue?)
}

protocol ClaimConfirmDataPassing {
    var dataStore: ClaimConfirmDataStore? { get }
}

class ClaimConfirmRouter: NSObject, ClaimConfirmRoutingLogic, ClaimConfirmDataPassing {

    weak var viewController: ClaimConfirmViewController?
    var dataStore: ClaimConfirmDataStore?

    // MARK: Routing

    func routeToSendFax(segue: UIStoryboardSegue?) {
        let vc = UIStoryboard.getVC(name: .claim, vcName: ClaimSendFaxViewController.identifier) as! ClaimSendFaxViewController
        navigateToSendFax(source: viewController!, destination: vc)
    }

    // MARK: Navigation

    func navigateToSendFax(source: ClaimConfirmViewController, destination: ClaimSendFaxViewController) {
        source.show(destination, sender: nil)
    }

    // MARK: Passing data

    //func passDataToSomewhere(source: ClaimConfirmDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
