//
//  CameraInteractor.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CameraBusinessLogic {
    func doSomething(request: Camera.Something.Request)
}

protocol CameraDataStore {
    //var name: String { get set }
}

class CameraInteractor: CameraBusinessLogic, CameraDataStore {
    var presenter: CameraPresentationLogic?
    var worker: CameraWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: Camera.Something.Request) {
        worker = CameraWorker()
        worker?.doSomeWork()

        let response = Camera.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
