//
//  ClaimNoPayoutPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClaimNoPayoutPresentationLogic {
    func presentSomething(response: ClaimNoPayout.Something.Response)
}

class ClaimNoPayoutPresenter: ClaimNoPayoutPresentationLogic {
    weak var viewController: ClaimNoPayoutDisplayLogic?

    // MARK: Do something

    func presentSomething(response: ClaimNoPayout.Something.Response) {
        let viewModel = ClaimNoPayout.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
