//
//  ClaimSendFaxPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClaimSendFaxPresentationLogic {
    func presentSectionModel(response: ClaimSendFax.SectionItem.Response)
}

class ClaimSendFaxPresenter: ClaimSendFaxPresentationLogic {
    weak var viewController: ClaimSendFaxDisplayLogic?

    // MARK: Do something

    func presentSectionModel(response: ClaimSendFax.SectionItem.Response) {
        let viewModel = ClaimSendFax.SectionItem.ViewModel(claimSectionModel: response.claimSectionModel)
        viewController?.displaySectionModel(viewModel: viewModel)
    }
}
