//
//  ClaimSignatureRouter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ClaimSignatureRoutingLogic {
    func routeToConfirm(segue: UIStoryboardSegue?)
}

protocol ClaimSignatureDataPassing {
    var dataStore: ClaimSignatureDataStore? { get }
}

class ClaimSignatureRouter: NSObject, ClaimSignatureRoutingLogic, ClaimSignatureDataPassing {

    weak var viewController: ClaimSignatureViewController?
    var dataStore: ClaimSignatureDataStore?

    // MARK: Routing

    func routeToConfirm(segue: UIStoryboardSegue?) {
        let vc = UIStoryboard.getVC(name: .claim, vcName: ClaimConfirmViewController.identifier) as! ClaimConfirmViewController
        navigateToConfirm(source: viewController!, destination: vc)
    }

    // MARK: Navigation

    func navigateToConfirm(source: ClaimSignatureViewController, destination: ClaimConfirmViewController) {
        source.show(destination, sender: nil)
    }

    // MARK: Passing data

    //func passDataToSomewhere(source: ClaimSignatureDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
