//
//  ClaimSignaturePresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClaimSignaturePresentationLogic {
    func presentSectionModel(response: ClaimSignature.SectionItem.Response)
}

class ClaimSignaturePresenter: ClaimSignaturePresentationLogic {
    weak var viewController: ClaimSignatureDisplayLogic?

    // MARK: Do something

    func presentSectionModel(response: ClaimSignature.SectionItem.Response) {
        let viewModel = ClaimSignature.SectionItem.ViewModel(claimSectionModel: response.claimSectionModel)
        viewController?.displaySectionModel(viewModel: viewModel)
    }
}
