//
//  ClaimSignatureWorker.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import BomappDM

class ClaimSignatureWorker {

    public func getClaimSectionModel() -> [ClaimSectionModel] {

        var model: [ClaimSectionModel] =
            [
                ClaimSectionModel(model: ClaimSectionID.section1,
                                  items: [
                                    ClaimModelItem(claimType: .headerTitle(title: "피보험자의\n자필 서명등록이\n필요합니다".bdmSetting(customFont: Font.light.font(size: 32), height: 34, letterSpacing: -1.0, color: UIColor(rgb: 0x3c7ae5)))),
                                    ClaimModelItem(claimType: .empty(height: 4)),
                                    ClaimModelItem(claimType: .headerDescription(description: "피보험자가 미성년일 경우\n법정 대리인이 서명해주세요".bdmSetting(customFont: Font.medium.font(size: 14), height: 20, letterSpacing: -0.5, color: UIColor(rgb: 0xa4a4a4)))),
                                    ClaimModelItem(claimType: .empty(height: 56)),
                                    ClaimModelItem(claimType: .underLine(color: UIColor(rgb: 0x4d4d4d), leading: 20))
                    ])
        ]

        model.append(ClaimSectionModel(model: ClaimSectionID.section2,
                                       items: [
                                        ClaimModelItem(claimType: .signatue(description: "피보험자"))
            ]))

        return model
    }
}
