//
//  ClaimInputContractRouter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ClaimInputContractRoutingLogic {
    func routeToInputClaim(segue: UIStoryboardSegue?)
}

protocol ClaimInputContractDataPassing {
    var dataStore: ClaimInputContractDataStore? { get }
}

class ClaimInputContractRouter: NSObject, ClaimInputContractRoutingLogic, ClaimInputContractDataPassing {
    weak var viewController: ClaimInputContractViewController?
    var dataStore: ClaimInputContractDataStore?

    // MARK: Routing

    func routeToInputClaim(segue: UIStoryboardSegue?) {
        let vc = UIStoryboard.getVC(name: .claim, vcName: ClaimInputClaimViewController.identifier) as! ClaimInputClaimViewController
        navigateToInputClaim(source: viewController!, destination: vc)
    }

    // MARK: Navigation

    func navigateToInputClaim(source: ClaimInputContractViewController, destination: ClaimInputClaimViewController) {
        source.show(destination, sender: nil)
    }

    // MARK: Passing data

    //func passDataToSomewhere(source: ClaimInputContractDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
