//
//  ClaimInputContractPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClaimInputContractPresentationLogic {
    func presentSectionModel(response: ClaimInputContract.SectionItem.Response)
}

class ClaimInputContractPresenter: ClaimInputContractPresentationLogic {

    weak var viewController: ClaimInputContractDisplayLogic?

    // MARK: Do something

    func presentSectionModel(response: ClaimInputContract.SectionItem.Response) {
        let viewModel = ClaimInputContract.SectionItem.ViewModel(claimSectionModel: response.claimSectionModel)
        viewController?.displaySectionModel(viewModel: viewModel)
    }
}
