//
//  ClaimInputContractWorker.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ClaimInputContractWorker {

    public func getClaimSectionModel() -> [ClaimSectionModel] {

        var model: [ClaimSectionModel] =
            [
                ClaimSectionModel(model: ClaimSectionID.section1,
                                  items: [
                                    ClaimModelItem(claimType: .headerDefault(title: "청구 내용 입력",
                                        description: "여러 번 치료받으신 경우, 최초 사고 일을 입력하시고\n치료기간 동안의 서류를 한번에 등록하시면 편합니다.")),
                                    ClaimModelItem(claimType: .empty(height: 56))
                    ])
        ]

        model.append(ClaimSectionModel(model: ClaimSectionID.section2,
                                       items: [
                                        ClaimModelItem(claimType: .infoCategoryType1(title: "피보험자 정보 입력", subTitle: NSAttributedString(), buttonTitle: "", isHiddenButton: true)),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .inputDefault(title: "이름", placeholder: "이름을 입력해주세요.", lineColor: UIColor(rgb: 0xefefef))),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .inputDefault(title: "주민등록번호", placeholder: "주민등록번호를 입력해주세요.", lineColor: UIColor(rgb: 0xefefef))),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .inputDefault(title: "휴대전화번호", placeholder: "휴대전화번호를 입력해주세요.", lineColor: UIColor(rgb: 0xefefef))),
                                        ClaimModelItem(claimType: .empty(height: 32))
            ]))

        model.append(ClaimSectionModel(model: ClaimSectionID.section3,
                                       items: [
                                        ClaimModelItem(claimType: .infoCategoryType1(title: "보험 수익자 정보", subTitle: NSAttributedString(), buttonTitle: "피보험자와 동일합니다", isHiddenButton: false)),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .inputDefault(title: "이름", placeholder: "이름을 입력해주세요.", lineColor: UIColor(rgb: 0xefefef))),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .inputDefault(title: "주민등록번호", placeholder: "주민등록번호를 입력해주세요.", lineColor: UIColor(rgb: 0xefefef))),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .inputDefault(title: "휴대전화번호", placeholder: "휴대전화번호를 입력해주세요.", lineColor: UIColor(rgb: 0xefefef))),
                                        ClaimModelItem(claimType: .empty(height: 32))
                                        ]))

        model.append(ClaimSectionModel(model: ClaimSectionID.section4,
                                       items: [
                                        ClaimModelItem(claimType: .infoCategoryType1(title: "보험금 수령할 계좌", subTitle: NSAttributedString(), buttonTitle: "", isHiddenButton: true)),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .inputDefault(title: "은행명", placeholder: "은행명을 입력해주세요.", lineColor: UIColor(rgb: 0xefefef))),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .inputDefault(title: "예금주", placeholder: "예금주를 입력해주세요.", lineColor: UIColor(rgb: 0xefefef))),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .inputDefault(title: "계좌번호", placeholder: "계좌번호를 입력해주세요.", lineColor: UIColor(rgb: 0xefefef))),
                                        ClaimModelItem(claimType: .empty(height: 50))
                                        ]))

        return model
    }
}
