//
//  ClaimRequireDocListRouter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ClaimRequireDocListRoutingLogic {
    func routeToRequireDocInfo(segue: UIStoryboardSegue?)
    func routeToSignature(segue: UIStoryboardSegue?)
    func routeToImageViewer(segue: UIStoryboardSegue?, index: Int)
}

protocol ClaimRequireDocListDataPassing {
    var dataStore: ClaimRequireDocListDataStore? { get }
}

class ClaimRequireDocListRouter: NSObject, ClaimRequireDocListRoutingLogic, ClaimRequireDocListDataPassing {
    weak var viewController: ClaimRequireDocListViewController?
    var dataStore: ClaimRequireDocListDataStore?

    // MARK: Routing

    func routeToRequireDocInfo(segue: UIStoryboardSegue?) {
        let vc = UIStoryboard.getVC(name: .claim, vcName: ClaimRequireDocInfoViewController.identifier) as! ClaimRequireDocInfoViewController
        navigateToRequireDocInfo(source: viewController!, destination: vc)
    }

    func routeToSignature(segue: UIStoryboardSegue?) {
        let vc = UIStoryboard.getVC(name: .claim, vcName: ClaimSignatureViewController.identifier) as! ClaimSignatureViewController
        navigateToSignature(source: viewController!, destination: vc)
    }

    func routeToImageViewer(segue: UIStoryboardSegue?, index: Int) {
    let vc = UIStoryboard.getVC(name: .camera, vcName: CameraPreviewAssetListVC.identifier) as! CameraPreviewAssetListVC
        vc.imageList.accept(ClaimSingleton.instance.requiredDocuments.value)
        vc.index = index
        vc.completeHandler = { assets in
            ClaimSingleton.instance.requiredDocuments.accept(assets)
        }
        navigateToImageViewer(source: viewController!, destination: vc)
    }

    // MARK: Navigation

    func navigateToRequireDocInfo(source: ClaimRequireDocListViewController, destination: ClaimRequireDocInfoViewController) {
        source.present(destination, animated: true, completion: nil)
    }

    func navigateToSignature(source: ClaimRequireDocListViewController, destination: ClaimSignatureViewController) {
        source.show(destination, sender: nil)
    }

    func navigateToImageViewer(source: ClaimRequireDocListViewController, destination: CameraPreviewAssetListVC) {
        source.present(destination, animated: true, completion: nil)
    }
}
