//
//  ClaimRequireDocListWorker.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ClaimRequireDocListWorker {

    public func getClaimSectionModel() -> [ClaimSectionModel] {

        var model: [ClaimSectionModel] =
            [
                ClaimSectionModel(model: ClaimSectionID.section1,
                                  items: [
                                    ClaimModelItem(claimType: .headerDefault(title: "구비서류 등록",
                                        description: "서류 등록 시, Wi-Fi에 연결되지 않은 경우,\n요금제에 따라 데이터 사용 요금이 부과될 수 있습니다.")),
                                    ClaimModelItem(claimType: .empty(height: 56)),
                                    ClaimModelItem(claimType: .underLine(color: UIColor(rgb: 0x4d4d4d), leading: 20)),
                                    ClaimModelItem(claimType: .empty(height: 32))

                    ])
        ]

        var modelItems: [ClaimModelItem] = []

        for doc in ClaimSingleton.instance.requiredDocuments.value {
            modelItems.append(ClaimModelItem(claimType: .galleryImage(asset: doc)))
        }
        modelItems.append(ClaimModelItem(claimType: .addImage()))

        model.append(ClaimSectionModel(model: ClaimSectionID.section2,
                              items: modelItems))

        model.append(ClaimSectionModel(model: ClaimSectionID.section3,
                                       items: [
                                        ClaimModelItem(claimType: .empty(height: 20))

            ]))

        return model
    }
}
