//
//  ClaimRequireDocListViewController.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxCocoa
import RxSwift
import Async

protocol ClaimRequireDocListDisplayLogic: class {
    func displaySectionModel(viewModel: ClaimRequireDocList.SectionItem.ViewModel)
}

class ClaimRequireDocListViewController: ClaimBaseViewController, ClaimRequireDocListDisplayLogic {
    var interactor: ClaimRequireDocListBusinessLogic?
    var router: (NSObjectProtocol & ClaimRequireDocListRoutingLogic & ClaimRequireDocListDataPassing)?

    let claim = ClaimSingleton.instance

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = ClaimRequireDocListInteractor()
        let presenter = ClaimRequireDocListPresenter()
        let router = ClaimRequireDocListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()

        interactor?.getSectionModel()
        configure()
    }

    private let disposeBag = DisposeBag()

    public let models = BehaviorRelay<[ClaimSectionModel]>(value: [])

    @IBOutlet weak var backBtn: UIButton!
    @IBOutlet weak var closeBtn: UIButton!
    @IBOutlet weak var bottomBtn: UIButton! {
        didSet {
            bottomBtn.setDefaultBottomBtnAttribute()
        }
    }

    // MARK: Do something

    func displaySectionModel(viewModel: ClaimRequireDocList.SectionItem.ViewModel) {
        models.accept(viewModel.claimSectionModel)
    }
}

extension ClaimRequireDocListViewController {

    private func configure() {
        configureUI()
        configureRx()
    }

    private func configureUI() {

    }

    private func configureRx() {
        models.bind(to: cv.rx.items(dataSource: dataSource)).disposed(by: self.disposeBag)

        cv.rx.itemSelected.bind(onNext: selectItem).disposed(by: disposeBag)

        claim.requiredDocuments.accept(claim.requiredDocuments.value)
        claim.requiredDocuments.subscribe(onNext: { [weak self] (_) in
            guard let self = self else { return }
            self.interactor?.getSectionModel()
        }).disposed(by: disposeBag)

        self.backBtn.rx.tap
            .subscribe(onNext: {
                self.navigationController?.popViewController(animated: true)
            }).disposed(by: disposeBag)

        self.closeBtn.rx.tap
            .subscribe(onNext: {
                //                self.navigationController?.popViewController(animated: true)
            }).disposed(by: disposeBag)

        self.bottomBtn.rx.tap
            .subscribe(onNext: {
                                self.router?.routeToSignature(segue: nil)
            }).disposed(by: disposeBag)
    }
}

extension ClaimRequireDocListViewController {

    func selectItem(_ indexPath: IndexPath) {

        if indexPath.item == claim.requiredDocuments.value.count {
            claim.addImage(self) { (_) in

                // 이미지를 추가하는 프리젠터로 이동해야함
                //                Async.main(after: 0.3, {
                //                    self.cv.scrollToItem(at: IndexPath(item: self.claim.requiredDocuments.value.count, section: 2), at: .bottom, animated: true)
                //                })
            }
        } else {
            router?.routeToImageViewer(segue: nil, index: indexPath.item)
        }
    }
}
