//
//  ClaimMainRouter.swift
//  Bomapp
//
//  Created by rowkaxl on 25/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ClaimMainRoutingLogic {
    func routeToGuide(segue: UIStoryboardSegue?)
    func routeToClaimNew(segue: UIStoryboardSegue?)
    func routeToClaimModify(segue: UIStoryboardSegue?)
//    func routeToClaimAddDocuments(segue: UIStoryboardSegue?)
//    func routeToClaimCopyDataWithoutInsurance(segue: UIStoryboardSegue?)
    func routeToPDFViewer(segue: UIStoryboardSegue?)
//    func routeToPayout(segue: UIStoryboardSegue?)
//    func routeToNoPayout(segue: UIStoryboardSegue?)
}

protocol ClaimMainDataPassing {
    var dataStore: ClaimMainDataStore? { get }
}

class ClaimMainRouter: NSObject, ClaimMainRoutingLogic, ClaimMainDataPassing {

    weak var viewController: ClaimMainViewController?
    var dataStore: ClaimMainDataStore?

    // MARK: Routing

    func routeToGuide(segue: UIStoryboardSegue?) {

        let vc = UIStoryboard.getVC(name: .claim, vcName: ClaimGuideViewController.identifier) as! ClaimGuideViewController
        navigateToGuide(source: viewController!, destination: vc)
    }

    func routeToClaimNew(segue: UIStoryboardSegue?) {
        let vc = UIStoryboard.getVC(name: .claim, vcName: ClaimIntroViewController.identifier) as! ClaimIntroViewController
        navigateToClaimNew(source: viewController!, destination: vc)
    }

    func routeToClaimModify(segue: UIStoryboardSegue?) {
        let vc = UIStoryboard.getVC(name: .claim, vcName: ClaimSelectInsuranceViewController.identifier) as! ClaimSelectInsuranceViewController
        navigateToClaimModify(source: viewController!, destination: vc)
    }

    func routeToPDFViewer(segue: UIStoryboardSegue?) {
        let vc = UIStoryboard.getVC(name: .claim, vcName: PDFViewerViewController.identifier) as! PDFViewerViewController
        var ds = vc.router!.dataStore!
        passDataToPDFViewer(source: dataStore!, destination: &ds)
        navigateToPDFViewer(source: viewController!, destination: vc)
    }

    // MARK: Navigation

    func navigateToGuide(source: ClaimMainViewController, destination: ClaimGuideViewController) {
//        source.show(destination, sender: nil)
        source.present(destination, animated: true) {
        }
    }

    func navigateToClaimNew(source: ClaimMainViewController, destination: ClaimIntroViewController) {
        source.show(destination, sender: nil)
    }

    func navigateToClaimModify(source: ClaimMainViewController, destination: ClaimSelectInsuranceViewController) {
        source.show(destination, sender: nil)
    }

    func navigateToPDFViewer(source: ClaimMainViewController, destination: PDFViewerViewController) {
        source.present(destination, animated: true)
    }

    // MARK: Passing data

    func passDataToPDFViewer(source: ClaimMainDataStore, destination: inout PDFViewerDataStore) {
//        destination.pdfURL = 
    }
}
