//
//  ClaimMainPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 25/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClaimMainPresentationLogic {
    func presentClaimList(response: ClaimMain.ClaimList.Response)
    func presentMedicalHistory(response: ClaimMain.MedicalList.Response)
    func presentNewClaim()
    func presentModifyClaim()
    func presentClaimFax()
    func presentOtherClaim()
    func presentModifyFaxNumClaim()
    func presentNoPayoutClaim()
}

class ClaimMainPresenter: ClaimMainPresentationLogic {
    weak var viewController: ClaimMainDisplayLogic?

    // MARK: Do something

    func presentClaimList(response: ClaimMain.ClaimList.Response) {
        let viewModel = ClaimMain.ClaimList.ViewModel(claimList: response.claimList, claimSectionModel: response.claimSectionModel)
        viewController?.displayClaimList(viewModel: viewModel)
    }

    func presentMedicalHistory(response: ClaimMain.MedicalList.Response) {
        let viewModel = ClaimMain.MedicalList.ViewModel(medicalHistoryList: response.medicalHistoryList, claimSectionModel: response.claimSectionModel)
        viewController?.displayMedicalHistory(viewModel: viewModel)
    }

    func presentNewClaim() {
        viewController?.displayNewClaim()
    }

    func presentModifyClaim() {
        viewController?.displayModifyClaim()
    }

    func presentClaimFax() {
        viewController?.displayClaimFax()
    }

    func presentOtherClaim() {
        viewController?.displayOtherClaim()
    }

    func presentModifyFaxNumClaim() {
        viewController?.displayModifyFaxNumClaim()
    }

    func presentNoPayoutClaim() {
        viewController?.displayNoPayoutClaim()
    }
}
