//
//  CameraPreviewAssetListPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CameraPreviewAssetListPresentationLogic {
    func presentSomething(response: CameraPreviewAssetList.Something.Response)
}

class CameraPreviewAssetListPresenter: CameraPreviewAssetListPresentationLogic {
    weak var viewController: CameraPreviewAssetListDisplayLogic?

    // MARK: Do something

    func presentSomething(response: CameraPreviewAssetList.Something.Response) {
        let viewModel = CameraPreviewAssetList.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
