//
//  CameraPreviewAssetListViewController.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CameraPreviewAssetListDisplayLogic: class {
    func displaySomething(viewModel: CameraPreviewAssetList.Something.ViewModel)
}

class CameraPreviewAssetListViewController: UIViewController, CameraPreviewAssetListDisplayLogic {
    var interactor: CameraPreviewAssetListBusinessLogic?
    var router: (NSObjectProtocol & CameraPreviewAssetListRoutingLogic & CameraPreviewAssetListDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = CameraPreviewAssetListInteractor()
        let presenter = CameraPreviewAssetListPresenter()
        let router = CameraPreviewAssetListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }

    // MARK: Do something

    //@IBOutlet weak var nameTextField: UITextField!

    func doSomething() {
        let request = CameraPreviewAssetList.Something.Request()
        interactor?.doSomething(request: request)
    }

    func displaySomething(viewModel: CameraPreviewAssetList.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
