//
//  CameraPreviewAssetListInteractor.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CameraPreviewAssetListBusinessLogic {
    func doSomething(request: CameraPreviewAssetList.Something.Request)
}

protocol CameraPreviewAssetListDataStore {
    //var name: String { get set }
}

class CameraPreviewAssetListInteractor: CameraPreviewAssetListBusinessLogic, CameraPreviewAssetListDataStore {
    var presenter: CameraPreviewAssetListPresentationLogic?
    var worker: CameraPreviewAssetListWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: CameraPreviewAssetList.Something.Request) {
        worker = CameraPreviewAssetListWorker()
        worker?.doSomeWork()

        let response = CameraPreviewAssetList.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
