//
//  ClaimIntroRouter.swift
//  Bomapp
//
//  Created by rowkaxl on 06/03/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ClaimIntroRoutingLogic {
    func routeToSelectInsurance(segue: UIStoryboardSegue?)
    func routeToGuide(segue: UIStoryboardSegue?)
}

protocol ClaimIntroDataPassing {
    var dataStore: ClaimIntroDataStore? { get }
}

class ClaimIntroRouter: NSObject, ClaimIntroRoutingLogic, ClaimIntroDataPassing {
    weak var viewController: ClaimIntroViewController?
    var dataStore: ClaimIntroDataStore?

    // MARK: Routing

    func routeToSelectInsurance(segue: UIStoryboardSegue?) {

        let vc = UIStoryboard.getVC(name: .claim, vcName: ClaimSelectInsuranceViewController.identifier) as! ClaimSelectInsuranceViewController
        navigateToSelectInsurance(source: viewController!, destination: vc)
    }

    func routeToGuide(segue: UIStoryboardSegue?) {

        let vc = UIStoryboard.getVC(name: .claim, vcName: ClaimGuideViewController.identifier) as! ClaimGuideViewController
        navigateToGuide(source: viewController!, destination: vc)
    }

    // MARK: Navigation

    func navigateToSelectInsurance(source: ClaimIntroViewController, destination: ClaimSelectInsuranceViewController) {
      source.show(destination, sender: nil)
    }

    func navigateToGuide(source: ClaimIntroViewController, destination: ClaimGuideViewController) {
        //        source.show(destination, sender: nil)
        source.present(destination, animated: true) {
        }
    }

    // MARK: Passing data

    //func passDataToSomewhere(source: ClaimIntroDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
