//
//  ClaimIntroInteractor.swift
//  Bomapp
//
//  Created by rowkaxl on 06/03/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClaimIntroBusinessLogic {
    func getSectionModel()
}

protocol ClaimIntroDataStore {
    //var name: String { get set }
}

class ClaimIntroInteractor: ClaimIntroBusinessLogic, ClaimIntroDataStore {
    var presenter: ClaimIntroPresentationLogic?
    var worker = ClaimIntroWorker()

    // MARK: getSectionModel

    func getSectionModel() {

        let sectionModel = self.worker.getClaimSectionModel()
        let response = ClaimIntro.SectionItem.Response(claimSectionModel: sectionModel)
        self.presenter?.presentSectionModel(response: response)
    }
}
