//
//  ClaimRequireDocListPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClaimRequireDocListPresentationLogic {
    func presentSectionModel(response: ClaimRequireDocList.SectionItem.Response)
}

class ClaimRequireDocListPresenter: ClaimRequireDocListPresentationLogic {
    weak var viewController: ClaimRequireDocListDisplayLogic?

    // MARK: Do something

    func presentSectionModel(response: ClaimRequireDocList.SectionItem.Response) {
        let viewModel = ClaimRequireDocList.SectionItem.ViewModel(claimSectionModel: response.claimSectionModel)
        viewController?.displaySectionModel(viewModel: viewModel)
    }
}
