//
//  ImageViewerInteractor.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageViewerBusinessLogic {
    func doSomething(request: ImageViewer.Something.Request)
}

protocol ImageViewerDataStore {
    //var name: String { get set }
}

class ImageViewerInteractor: ImageViewerBusinessLogic, ImageViewerDataStore {
    var presenter: ImageViewerPresentationLogic?
    var worker: ImageViewerWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: ImageViewer.Something.Request) {
        worker = ImageViewerWorker()
        worker?.doSomeWork()

        let response = ImageViewer.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
