//
//  ClaimNoPayoutInteractor.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClaimNoPayoutBusinessLogic {
    func doSomething(request: ClaimNoPayout.Something.Request)
}

protocol ClaimNoPayoutDataStore {
    //var name: String { get set }
}

class ClaimNoPayoutInteractor: ClaimNoPayoutBusinessLogic, ClaimNoPayoutDataStore {
    var presenter: ClaimNoPayoutPresentationLogic?
    var worker: ClaimNoPayoutWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: ClaimNoPayout.Something.Request) {
        worker = ClaimNoPayoutWorker()
        worker?.doSomeWork()

        let response = ClaimNoPayout.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
