//
//  ClaimSendFaxRouter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ClaimSendFaxRoutingLogic {
    func routeToResult(segue: UIStoryboardSegue?)
}

protocol ClaimSendFaxDataPassing {
    var dataStore: ClaimSendFaxDataStore? { get }
}

class ClaimSendFaxRouter: NSObject, ClaimSendFaxRoutingLogic, ClaimSendFaxDataPassing {
    weak var viewController: ClaimSendFaxViewController?
    var dataStore: ClaimSendFaxDataStore?

    // MARK: Routing

    func routeToResult(segue: UIStoryboardSegue?) {
        let vc = UIStoryboard.getVC(name: .claim, vcName: ClaimResultViewController.identifier) as! ClaimResultViewController
        navigateToResult(source: viewController!, destination: vc)
    }

    // MARK: Navigation

    func navigateToResult(source: ClaimSendFaxViewController, destination: ClaimResultViewController) {
        source.show(destination, sender: nil)
    }

    // MARK: Passing data

    //func passDataToSomewhere(source: ClaimSendFaxDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
