//
//  ClaimSendFaxWorker.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import BomappDM

class ClaimSendFaxWorker {

    let claim = ClaimSingleton.instance

    public func getClaimSectionModel() -> [ClaimSectionModel] {

        var model: [ClaimSectionModel] =
            [
                ClaimSectionModel(model: ClaimSectionID.section1,
                                  items: [
                                    ClaimModelItem(claimType: .headerDefault(title: "팩스번호 확인",
                                        description: "팩스로 청구가 접수될 예정입니다.\n보험사별 팩스번호를 확인해주세요.")),
                                    ClaimModelItem(claimType: .empty(height: 56)),
                                    ClaimModelItem(claimType: .underLine(color: UIColor(rgb: 0x4d4d4d), leading: 20))
                    ])
        ]
        
        
        var modelItems: [ClaimModelItem] = []
        for model in claim.insuranceList.value {
            modelItems.append(ClaimModelItem(claimType: .empty(height: 20)))
            modelItems.append(ClaimModelItem(claimType: .insuranceLogoTitle(logoNumber: model.code ?? "", insuTitle: model.name ?? "", isDisable: false, buttonTitle: "전화걸기".bdmSetting(customFont: Font.medium.font(size: 12), height: 16, letterSpacing: -0.5, color: UIColor(rgb: 0x949494), underLine: true), buttonImage: nil)))
            modelItems.append(ClaimModelItem(claimType: .empty(height: 20)))
            modelItems.append(ClaimModelItem(claimType: .inputDefault(title: "팩스번호", placeholder: "상담원과 통화 후 팩스번호를 입력해주세요.", lineColor: UIColor(rgb: 0xefefef))))
        }

        model.append(ClaimSectionModel(model: ClaimSectionID.section2,
                                       items: modelItems))

        model.append(ClaimSectionModel(model: ClaimSectionID.section3,
                                       items: [
                                        ClaimModelItem(claimType: .empty(height: 50))
            ]))

        return model
    }
}
