//
//  CameraPreviewListPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CameraPreviewListPresentationLogic {
    func presentSomething(response: CameraPreviewList.Something.Response)
}

class CameraPreviewListPresenter: CameraPreviewListPresentationLogic {
    weak var viewController: CameraPreviewListDisplayLogic?

    // MARK: Do something

    func presentSomething(response: CameraPreviewList.Something.Response) {
        let viewModel = CameraPreviewList.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
