//
//  ClaimMainModels.swift
//  Bomapp
//
//  Created by rowkaxl on 25/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift
import BomappDM

enum ClaimMain {
    // MARK: Use cases

    enum ClaimList {
        struct Request {

        }
        struct Response {
            var claimList: Results<ClaimItem>
            var claimSectionModel: [ClaimSectionModel]
        }
        struct ViewModel {
            var claimList: Results<ClaimItem>
            var claimSectionModel: [ClaimSectionModel]
//            var faxUuids: [String]
        }
    }

    enum MedicalList {
        struct Request {

        }
        struct Response {
            var medicalHistoryList: Results<ClaimMedicalHistoryItem>
            var claimSectionModel: [ClaimSectionModel]
        }
        struct ViewModel {
            var medicalHistoryList: Results<ClaimMedicalHistoryItem>
            var claimSectionModel: [ClaimSectionModel]
        }
    }
}
