//
//  GalleryListInteractor.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GalleryListBusinessLogic {
    func doSomething(request: GalleryList.Something.Request)
}

protocol GalleryListDataStore {
    //var name: String { get set }
}

class GalleryListInteractor: GalleryListBusinessLogic, GalleryListDataStore {
    var presenter: GalleryListPresentationLogic?
    var worker: GalleryListWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: GalleryList.Something.Request) {
        worker = GalleryListWorker()
        worker?.doSomeWork()

        let response = GalleryList.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
