//
//  GalleryListPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GalleryListPresentationLogic {
    func presentSomething(response: GalleryList.Something.Response)
}

class GalleryListPresenter: GalleryListPresentationLogic {
    weak var viewController: GalleryListDisplayLogic?

    // MARK: Do something

    func presentSomething(response: GalleryList.Something.Response) {
        let viewModel = GalleryList.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
