//
//  ClaimRequestPopupInteractor.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClaimRequestPopupBusinessLogic {
    func doSomething(request: ClaimRequestPopup.Something.Request)
}

protocol ClaimRequestPopupDataStore {
    //var name: String { get set }
}

class ClaimRequestPopupInteractor: ClaimRequestPopupBusinessLogic, ClaimRequestPopupDataStore {
    var presenter: ClaimRequestPopupPresentationLogic?
    var worker: ClaimRequestPopupWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: ClaimRequestPopup.Something.Request) {
        worker = ClaimRequestPopupWorker()
        worker?.doSomeWork()

        let response = ClaimRequestPopup.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
