//
//  ClaimRequireDocWorker.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import BomappDM

class ClaimRequireDocWorker {

    public func getClaimSectionModel() -> [ClaimSectionModel] {

        var model: [ClaimSectionModel] =
            [
                ClaimSectionModel(model: ClaimSectionID.section1,
                                  items: [
                                    ClaimModelItem(claimType: .headerDefault(title: "구비서류 등록",
                                        description: "구비서류를 확인하시고 한번에 등록하시면 편합니다.\n사진이 흔들리지 않게 조심해주세요.")),
                                    ClaimModelItem(claimType: .headerButton(buttonTitle: "구비서류 안내")),
                                    ClaimModelItem(claimType: .empty(height: 32)),
                                    ClaimModelItem(claimType: .underLine(color: UIColor(rgb: 0x4d4d4d), leading: 20))

                    ])
        ]

        model.append(ClaimSectionModel(model: ClaimSectionID.section2,
                                       items: [
                                        ClaimModelItem(claimType: .empty(height: 24)),
                                        ClaimModelItem(claimType: .dotDesc(description: "촬영 시 그림자가 생기지 않도록 주의해주세요.\n᛫ 흔들리지 않게 초점을 잘 맞춰서 촬영해주세요.".bdmSetting(customFont: Font.medium.font(size: 14), height: 20, letterSpacing: -0.5, color: UIColor(rgb: 0x070e1a)))),
                                        ClaimModelItem(claimType: .empty(height: 4)),
                                        ClaimModelItem(claimType: .dotDesc(description: "흔들리지 않게 초점을 잘 맞춰서 촬영해주세요.".bdmSetting(customFont: Font.medium.font(size: 14), height: 20, letterSpacing: -0.5, color: UIColor(rgb: 0x070e1a)))),
                                        ClaimModelItem(claimType: .empty(height: 4)),
                                        ClaimModelItem(claimType: .dotDesc(description: "필요한 서류를 모아서 한번에 찍고 등록하세요.".bdmSetting(customFont: Font.medium.font(size: 14), height: 20, letterSpacing: -0.5, color: UIColor(rgb: 0x070e1a))))

            ]))

        return model
    }
}
