//
//  ClaimRequireDocRouter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ClaimRequireDocRoutingLogic {
    func routeToRequireDocList(segue: UIStoryboardSegue?)
//    func routeToRequireDocInfo(segue: UIStoryboardSegue?)
//    func routeToSignature(segue: UIStoryboardSegue?)
}

protocol ClaimRequireDocDataPassing {
    var dataStore: ClaimRequireDocDataStore? { get }
}

class ClaimRequireDocRouter: NSObject, ClaimRequireDocRoutingLogic, ClaimRequireDocDataPassing {

    weak var viewController: ClaimRequireDocViewController?
    var dataStore: ClaimRequireDocDataStore?

    // MARK: Routing

    func routeToRequireDocList(segue: UIStoryboardSegue?) {
        let vc = UIStoryboard.getVC(name: .claim, vcName: ClaimRequireDocListViewController.identifier) as! ClaimRequireDocListViewController
        navigateToRequireDocList(source: viewController!, destination: vc)
    }

    // MARK: Navigation

    func navigateToRequireDocList(source: ClaimRequireDocViewController, destination: ClaimRequireDocListViewController) {
        source.show(destination, sender: nil)
    }

    // MARK: Passing data

    //func passDataToSomewhere(source: ClaimRequireDocDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
