//
//  ClaimSelectInsuranceWorker.swift
//  Bomapp
//
//  Created by rowkaxl on 25/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import RxCocoa
import SwiftyJSON

class ClaimSelectInsuranceWorker {

    let disposeBag = DisposeBag()

    func requestInsuranceCompToFax(handler: @escaping ((_ compList: JSON) -> Void)) {

        APIManager.request(target: Bomapp.getInsuranceCompToFax)
            .subscribe(onSuccess: { (code, json) in
            switch code {
            case .code2000: handler(json)
            default: handler(JSON())
            }
        })
        .disposed(by: disposeBag)
    }

    func requestInsurancePDFData(compCode: String, handler: @escaping ((_ compList: JSON) -> Void)) {

        APIManager.request(target: Bomapp.claimForm(compCode: compCode))
            .subscribe(onSuccess: { (code, json) in
                switch code {
                case .code2000: handler(json)
                default: handler(JSON())
                }
            })
            .disposed(by: disposeBag)
    }
}
