//
//  ClaimGuideInteractor.swift
//  Bomapp
//
//  Created by rowkaxl on 25/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClaimGuideBusinessLogic {
    func getSectionModel()
}

protocol ClaimGuideDataStore {
}

class ClaimGuideInteractor: ClaimGuideBusinessLogic, ClaimGuideDataStore {
    var presenter: ClaimGuidePresentationLogic?
    var worker = ClaimGuideWorker()

    // MARK: getSectionModel

    func getSectionModel() {

        let sectionModel = self.worker.getClaimSectionModel()
        let response = ClaimGuide.SectionItem.Response(claimSectionModel: sectionModel)
        self.presenter?.presentSectionModel(response: response)
    }
}
