//
//  CameraPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CameraPresentationLogic {
    func presentSomething(response: Camera.Something.Response)
}

class CameraPresenter: CameraPresentationLogic {
    weak var viewController: CameraDisplayLogic?

    // MARK: Do something

    func presentSomething(response: Camera.Something.Response) {
        let viewModel = Camera.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
