//
//  ClaimRequireDocInfoPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClaimRequireDocInfoPresentationLogic {
    func presentSomething(response: ClaimRequireDocInfo.Something.Response)
}

class ClaimRequireDocInfoPresenter: ClaimRequireDocInfoPresentationLogic {
    weak var viewController: ClaimRequireDocInfoDisplayLogic?

    // MARK: Do something

    func presentSomething(response: ClaimRequireDocInfo.Something.Response) {
        let viewModel = ClaimRequireDocInfo.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
