//
//  PDFViewerInteractor.swift
//  Bomapp
//
//  Created by rowkaxl on 27/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PDFViewerBusinessLogic {
    func getPDFData()
}

protocol PDFViewerDataStore {
    var pdfURL: String! { get set }
}

class PDFViewerInteractor: PDFViewerBusinessLogic, PDFViewerDataStore {

    var presenter: PDFViewerPresentationLogic?
    var worker: PDFViewerWorker?
    var pdfURL: String!

    // MARK: Do something

    func getPDFData() {

        let response = PDFViewer.PDFItem.Response(pdfURL: pdfURL)
        presenter?.presentPDFdata(response: response)
    }
}
