//
//  ClaimRequireDocPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClaimRequireDocPresentationLogic {
    func presentSectionModel(response: ClaimRequireDoc.SectionItem.Response)
}

class ClaimRequireDocPresenter: ClaimRequireDocPresentationLogic {
    weak var viewController: ClaimRequireDocDisplayLogic?

    // MARK: Do something

    func presentSectionModel(response: ClaimRequireDoc.SectionItem.Response) {
        let viewModel = ClaimRequireDoc.SectionItem.ViewModel(claimSectionModel: response.claimSectionModel)
        viewController?.displaySectionModel(viewModel: viewModel)
    }
}
