//
//  ClaimRequestPopupPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClaimRequestPopupPresentationLogic {
    func presentSomething(response: ClaimRequestPopup.Something.Response)
}

class ClaimRequestPopupPresenter: ClaimRequestPopupPresentationLogic {
    weak var viewController: ClaimRequestPopupDisplayLogic?

    // MARK: Do something

    func presentSomething(response: ClaimRequestPopup.Something.Response) {
        let viewModel = ClaimRequestPopup.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
