//
//  ImageViewerPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageViewerPresentationLogic {
    func presentSomething(response: ImageViewer.Something.Response)
}

class ImageViewerPresenter: ImageViewerPresentationLogic {
    weak var viewController: ImageViewerDisplayLogic?

    // MARK: Do something

    func presentSomething(response: ImageViewer.Something.Response) {
        let viewModel = ImageViewer.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
