//
//  ClaimConfirmWorker.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import BomappDM

class ClaimConfirmWorker {

    let claim = ClaimSingleton.instance

    public func getClaimSectionModel() -> [ClaimSectionModel] {

        var model: [ClaimSectionModel] =
            [
                ClaimSectionModel(model: ClaimSectionID.section1,
                                  items: [
                                    ClaimModelItem(claimType: .headerDefault(title: "청구 내용 확인",
                                        description: "아래 내용으로 청구가 접수될 예정입니다.\n정확히 입력이 됐는지 다시 한번 확인해주세요.")),
                                    ClaimModelItem(claimType: .empty(height: 56))
                    ])
        ]

        model.append(ClaimSectionModel(model: ClaimSectionID.section2,
                                       items: [
                                        ClaimModelItem(claimType: .infoCategoryType1(title: "청구 보험사", subTitle: NSAttributedString(), buttonTitle: "수정하기", isHiddenButton: false)),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .infoType1(title: "보험사", description: claim.insuranceComps)),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .underLine(color: UIColor(rgb: 0xefefef), leading: 20)),
                                        ClaimModelItem(claimType: .empty(height: 32))
            ]))

        model.append(ClaimSectionModel(model: ClaimSectionID.section3,
                                       items: [
                                        ClaimModelItem(claimType: .infoCategoryType1(title: "계약 정보", subTitle: NSAttributedString(), buttonTitle: "수정하기", isHiddenButton: false)),
                                        ClaimModelItem(claimType: .empty(height: 20)),

                                        ClaimModelItem(claimType: .infoType2(description: "계약 정보".bdmSetting(customFont: Font.semiBold.font(size: 12), height: 16, letterSpacing: -0.5, color: UIColor(rgb: 0xa4a4a4)))),
                                        ClaimModelItem(claimType: .empty(height: 8)),
                                        ClaimModelItem(claimType: .infoType1(title: "이름", description: claim.insured)),
                                        ClaimModelItem(claimType: .empty(height: 8)),
                                        ClaimModelItem(claimType: .infoType1(title: "주민등록번호", description: claim.regiNumber)),
                                        ClaimModelItem(claimType: .empty(height: 8)),
                                        ClaimModelItem(claimType: .infoType1(title: "휴대전화번호", description: claim.telNumber)),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .underLine(color: UIColor(rgb: 0xefefef), leading: 20)),
                                        ClaimModelItem(claimType: .empty(height: 20)),

                                        ClaimModelItem(claimType: .infoType2(description: "보험 수익자".bdmSetting(customFont: Font.semiBold.font(size: 12), height: 16, letterSpacing: -0.5, color: UIColor(rgb: 0xa4a4a4)))),
                                        ClaimModelItem(claimType: .empty(height: 8)),
                                        ClaimModelItem(claimType: .infoType1(title: "이름", description: claim.claimant)),
                                        ClaimModelItem(claimType: .empty(height: 8)),
                                        ClaimModelItem(claimType: .infoType1(title: "주민등록번호", description: claim.claimantRegiNumber)),
                                        ClaimModelItem(claimType: .empty(height: 8)),
                                        ClaimModelItem(claimType: .infoType1(title: "휴대전화번호", description: claim.claimantTelNumber)),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .underLine(color: UIColor(rgb: 0xefefef), leading: 20)),
                                        ClaimModelItem(claimType: .empty(height: 20)),

                                        ClaimModelItem(claimType: .infoType2(description: "보험금 수령 계좌".bdmSetting(customFont: Font.semiBold.font(size: 12), height: 16, letterSpacing: -0.5, color: UIColor(rgb: 0xa4a4a4)))),
                                        ClaimModelItem(claimType: .empty(height: 8)),
                                        ClaimModelItem(claimType: .infoType1(title: "은행명", description: claim.bankName)),
                                        ClaimModelItem(claimType: .empty(height: 8)),
                                        ClaimModelItem(claimType: .infoType1(title: "계좌번호", description: claim.account)),
                                        ClaimModelItem(claimType: .empty(height: 8)),
                                        ClaimModelItem(claimType: .infoType1(title: "예금주", description: claim.accountHolder)),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .underLine(color: UIColor(rgb: 0xefefef), leading: 20)),
                                        ClaimModelItem(claimType: .empty(height: 32))
            ]))

        model.append(ClaimSectionModel(model: ClaimSectionID.section4,
                                       items: [
                                        ClaimModelItem(claimType: .infoCategoryType1(title: "청구 내용", subTitle: NSAttributedString(), buttonTitle: "수정하기", isHiddenButton: false)),
                                        ClaimModelItem(claimType: .empty(height: 20)),

                                        ClaimModelItem(claimType: .infoType1(title: "사고유형", description: claim.accidentType)),
                                        ClaimModelItem(claimType: .empty(height: 8)),
                                        ClaimModelItem(claimType: .infoType1(title: "사고(발병)일시", description: claim.accidentDate)),
                                        ClaimModelItem(claimType: .empty(height: 8)),
                                        ClaimModelItem(claimType: .infoType1(title: "진단며 또는 병명", description: claim.claimDate ?? " ")),
                                        ClaimModelItem(claimType: .empty(height: 20)),
                                        ClaimModelItem(claimType: .underLine(color: UIColor(rgb: 0xefefef), leading: 20)),
                                        ClaimModelItem(claimType: .empty(height: 32))
            ]))

        model.append(ClaimSectionModel(model: ClaimSectionID.section5,
                                       items: [
                                        ClaimModelItem(claimType: .infoCategoryType1(title: "구비서류", subTitle: NSAttributedString(), buttonTitle: "수정하기", isHiddenButton: false)),
                                        ClaimModelItem(claimType: .empty(height: 20))

            ]))

        var modelItems: [ClaimModelItem] = []

        for doc in ClaimSingleton.instance.requiredDocuments.value {
            modelItems.append(ClaimModelItem(claimType: .galleryImage(asset: doc)))
        }
        model.append(ClaimSectionModel(model: ClaimSectionID.section6,
                                       items: modelItems))

        model.append(ClaimSectionModel(model: ClaimSectionID.section7,
                                       items: [
                                        ClaimModelItem(claimType: .empty(height: 32))

            ]))

        return model
    }
}
