//
//  ClaimConfirmPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClaimConfirmPresentationLogic {
    func presentSectionModel(response: ClaimConfirm.SectionItem.Response)
}

class ClaimConfirmPresenter: ClaimConfirmPresentationLogic {
    weak var viewController: ClaimConfirmDisplayLogic?

    // MARK: Do something

    func presentSectionModel(response: ClaimConfirm.SectionItem.Response) {
        let viewModel = ClaimConfirm.SectionItem.ViewModel(claimSectionModel: response.claimSectionModel)
        viewController?.displaySectionModel(viewModel: viewModel)
    }
}
