//
//  ClaimInputClaimViewController.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxCocoa
import RxSwift

protocol ClaimInputClaimDisplayLogic: class {
    func displaySectionModel(viewModel: ClaimInputClaim.SectionItem.ViewModel)
    func displaySaveClaimSingleton()
}

class ClaimInputClaimViewController: ClaimBaseViewController, ClaimInputClaimDisplayLogic {
    var interactor: ClaimInputClaimBusinessLogic?
    var router: (NSObjectProtocol & ClaimInputClaimRoutingLogic & ClaimInputClaimDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = ClaimInputClaimInteractor()
        let presenter = ClaimInputClaimPresenter()
        let router = ClaimInputClaimRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()

        interactor?.getSectionModel()
        configure()
    }

    private let disposeBag = DisposeBag()

    public let models = BehaviorRelay<[ClaimSectionModel]>(value: [])

    @IBOutlet weak var backBtn: UIButton!
    @IBOutlet weak var closeBtn: UIButton!
    @IBOutlet weak var bottomBtn: UIButton! {
        didSet {
            bottomBtn.setDefaultBottomBtnAttribute()
        }
    }

    // MARK: Do something

    func displaySectionModel(viewModel: ClaimInputClaim.SectionItem.ViewModel) {
        models.accept(viewModel.claimSectionModel)
    }

    func displaySaveClaimSingleton() {
    }
}

extension ClaimInputClaimViewController {

    private func configure() {
        configureUI()
        configureRx()
    }

    private func configureUI() {

        buttonTabHandler = { buttonTitle in

            print(buttonTitle)

            switch buttonTitle {
            case "질병": break
            case "상해/재해": break
            default: break
            }
        }
    }

    private func configureRx() {
        models.bind(to: cv.rx.items(dataSource: dataSource)).disposed(by: self.disposeBag)

        self.backBtn.rx.tap
            .subscribe(onNext: {
                self.navigationController?.popViewController(animated: true)
            }).disposed(by: disposeBag)

        self.closeBtn.rx.tap
            .subscribe(onNext: {
                //                self.navigationController?.popViewController(animated: true)
            }).disposed(by: disposeBag)

        self.bottomBtn.rx.tap
            .subscribe(onNext: {

                // 밸리데이션
                //                    PopupManager.confirmPopup(title: "안내",
                //                                              content: "청구하실 보험사를 선택해주세요.")
                //                        .subscribe().disposed(by: self.disposeBag)

                //                self.interactor?.saveSelectInsurance(selectedIndexPaths: selectedIndexPaths, compList: compList)

                self.router?.routeToRequireDoc(segue: nil)

            }).disposed(by: disposeBag)
    }
}
