//
//  ClaimInputClaimPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 26/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClaimInputClaimPresentationLogic {
    func presentSectionModel(response: ClaimInputClaim.SectionItem.Response)
}

class ClaimInputClaimPresenter: ClaimInputClaimPresentationLogic {
    weak var viewController: ClaimInputClaimDisplayLogic?

    // MARK: Do something

    func presentSectionModel(response: ClaimInputClaim.SectionItem.Response) {
        let viewModel = ClaimInputClaim.SectionItem.ViewModel(claimSectionModel: response.claimSectionModel)
        viewController?.displaySectionModel(viewModel: viewModel)
    }
}
