//
//  PDFViewerModels.swift
//  Bomapp
//
//  Created by rowkaxl on 27/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PDFViewer {
    // MARK: Use cases

    enum PDFItem {
        struct Request {

        }
        struct Response {
            var pdfURL: String
        }
        struct ViewModel {
            var pdfURL: String
        }
    }
}
