//
//  PDFViewerPresenter.swift
//  Bomapp
//
//  Created by rowkaxl on 27/02/2019.
//  Copyright (c) 2019 Redvelvet Ventures Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PDFViewerPresentationLogic {
    func presentPDFdata(response: PDFViewer.PDFItem.Response)
}

class PDFViewerPresenter: PDFViewerPresentationLogic {
    weak var viewController: PDFViewerDisplayLogic?

    // MARK: Do something

    func presentPDFdata(response: PDFViewer.PDFItem.Response) {
        let viewModel = PDFViewer.PDFItem.ViewModel(pdfURL: response.pdfURL)
        viewController?.displayPDFViewer(viewModel: viewModel)
    }
}
